feat: DW_lbsh wrapper in Chisel
chipsalliance/chisel-interface pull request #92
Opened 2024-05-26 05:26 UTC by SingularityKChen

+ write the Chisel wrapper for DW_lbsh;

2024-05-28 09:48 UTC, sequencer requested changes

2024-05-28 09:48 UTC, sequencer commented on dwbb/src/interface/DW_lbsh.scala
> +case class Parameter(AWidth: Int = 49, SHWidth: Int = 6)
```suggestion
case class Parameter(aWidth: Int = 49, shWidth: Int = 6)
```

2024-05-28 11:14 UTC, SingularityKChen commented on dwbb/src/interface/DW_lbsh.scala
> +case class Parameter(AWidth: Int = 49, SHWidth: Int = 6)
Done

2024-05-29 03:20 UTC, sequencer approved these changes

2024-05-29 03:20 UTC, merged